consensus-preprocess.pl
Use #!/usr/bin/env perl to search the PATH for perl
rather than hardcoding #!/usr/bin/perl.
=> consensus-preprocess.pl: Use #!/usr/bin/env perl

Makefile
Addresses CPP/CXX flags & `rm -f`; but not any HDF issues.
=> fixed CXX/CPP flags; rm -f

src/alignment/nanopolish_eventalign.cpp, src/hmm/nanopolish_emissions.h, src/main/nanopolish.cpp, src/nanopolish_poremodel.cpp, src/nanopolish_poremodel.h, src/nanopolish_squiggle_read.cpp, src/nanopolish_squiggle_read.h
This pull request adds stdv modelling as per the ONT documents and discussion. I separated the commits so that it's easier to review them one by one.
The main changes are:
- `SquiggleEvent` gets a precomputed `log_stdv` field.
- `PoreModelStateParams` gets `sd_lambda`, as well as precomputed `level_log_stdv` and `sd_log_lambda`.
- `PoreModel` keeps a `scaled_state` in addition to `state` and `scaled_parameters` arrays. The latter is now redundant, but some code still uses it, so I left it in to minimize changes.
- The emission code uses the new `scaled_state` to model both level and stdv.
Notably, the code that models stdv is still disabled by default. It can now be enabled by a command line switch.
=> Model stdv

.gitignore, src/alignment/nanopolish_eventalign.cpp, src/nanopolish_methyltrain.cpp, src/nanopolish_poremodel.cpp, src/nanopolish_poremodel.h, src/nanopolish_squiggle_read.h
Initial version of `methyltrain` that trains the model `sd_mean`. This is enabled by the `--stdv` cl option. The code compiles and runs, but I didn't check if the results are actually reasonable.
Apart from training `sd_mean`, I made a few changes to other ares:
- I moved some of the computation related to `PoreModelStateParams` inside that struct. The problem here is that IGs have 2 parameters but 3 are being used at various points, the problematic overlap being between lambda and sigma. Each time one of them (or eta) is changed, the other has to change, too.
- Inside `train_one_round`, I moved up (and actually enabled) the code that skips kmers that are not being updated. The loop still writes to the training file and the summary file before continuing. I'm not sure if this is intended, …
=> train sd_mean

src/nanopolish_methyltrain.cpp
sets var <- sqrt(var), and enables the setting of var by setting an argument to true
=> Enable recalibration of var, which actually scales SDs, by taking sqrt(var)

src/alignment/nanopolish_alignment_db.cpp, src/alignment/nanopolish_anchor.cpp, src/alignment/nanopolish_eventalign.cpp, src/common/nanopolish_alphabet.h, src/common/nanopolish_fast5_map.cpp, src/common/nanopolish_iupac.h, src/common/nanopolish_variant.h, src/common/progress.h, src/hmm/nanopolish_emissions.h, src/hmm/nanopolish_hmm_input_sequence.h, src/hmm/nanopolish_profile_hmm.cpp, src/hmm/nanopolish_profile_hmm.inl, src/hmm/nanopolish_transition_parameters.cpp, src/hmm/nanopolish_transition_parameters.h, src/main/nanopolish.cpp, src/nanopolish_call_variants.cpp, src/nanopolish_consensus.cpp, src/nanopolish_getmodel.cpp, src/nanopolish_methyltrain.cpp, src/nanopolish_poremodel.cpp, src/nanopolish_poremodel.h, src/nanopolish_scorereads.cpp, src/nanopolish_squiggle_read.cpp, src/nanopolish_squiggle_read.h, src/test/nanopolish_test.cpp
Cleaned up a variety of warnings. Most fall into one of: unused variable, incorrect constructor initialization order, signed vs unsigned comparison. Left a couple of TODOs where the original intent was unclear.
=> clean up warnings

src/nanopolish_scorereads.cpp
Fix a cut-and-paste error in nanopolish_scorereads.cpp usage documentation.
=> Fix cut-and-paste error in usage documentation

src/alignment/nanopolish_alignment_db.cpp, src/alignment/nanopolish_anchor.cpp, src/nanopolish_methyltrain.cpp, src/nanopolish_methyltrain.h, src/nanopolish_scorereads.cpp, src/nanopolish_squiggle_read.cpp, src/nanopolish_train_poremodel_from_basecalls.cpp
Calculating and returning the L1 residual as part of recalibrate_model(). I don't love having it as a separate parameter which has to be passed in invocations that don't need it, but the alternatives look messy - do the same thing with the bool about whether the recalibration happened, return a special residual value to specify bool=false (which I hate) or return a pair.
I'm not 100% sure what the right metric for the residual is - the L2 norm is just var, so I think var-scaled L1 norm seems right - it's a measure of the distance the means are off rather than just the spreads. But that will take some experimentation.
=> Calculate L1 residual when recalibrating model, return it as a parameter

Makefile, src/nanopolish_poremodel.cpp, src/nanopolish_poremodel.h, src/nanopolish_squiggle_read.cpp
Using -I in the C preprocessor flags adds the specified directories
to the search path. Taking advantage of this, we can use angle-brackets
for the include statements to avoid hardcoding the location of dependencies and
to ease use of externally installed versions.
=> Use angle-bracket includes to allow flexibile placement of dependencies

src/nanopolish_squiggle_read.cpp
I've applied this patch to the Debian package to keep up with the latest fast5 release. It looks like there was a simple API change introduced by https://github.com/mateidavid/fast5/commit/a9f711487cdcd8b83703292c9dd7a5e35869c70c. With this patch, I can build nanopolish and successfully run the test suite.
=> Update to latest fast5 release (0.5.6)

Dockerfile
`libhdf5.install` no longer exists as a target.   Addresses issue #47 .
=> Update Dockerfile make invocation

src/nanopolish_train_poremodel_from_basecalls.cpp, src/test/nanopolish_test.cpp, src/training_core.cpp, src/training_core.hpp
As discussed, since the training data contains event level means that are scaled down by `read_scale`, similarly `read_var` should be scaled down by `read_scale` before computing normal pdfs. I left in the old `read_var` field in the training data struct, though it's no longer used anywhere, as far as I can tell.
=> `read_var` should be scaled down by `read_scale`

src/alignment/nanopolish_alignment_db.cpp, src/common/logger.hpp, src/common/nanopolish_alphabet.h, src/nanopolish_call_methylation.cpp, src/nanopolish_call_variants.cpp, src/nanopolish_extract.cpp, src/nanopolish_methyltrain.cpp, src/nanopolish_phase_reads.cpp, src/nanopolish_poremodel.cpp, src/nanopolish_poremodel.h, src/nanopolish_squiggle_read.cpp, src/nanopolish_squiggle_read.h
- Updated code to use Fast5 0.6+, which contains built-in packing. Nanopolish should now be able to run directly on packed files.
- Fixed various `printf` format warnings.
- Fixed warning about inline pure virtual.
- Renamed `extract` option from `all` to `any` addressing #116.
=> Fast5 update

src/common/nanopolish_variant.cpp, src/nanopolish_call_variants.cpp
Hi Jared
As discussed, here is a patch for nanopolish that:
* produces a warning if nanopolish variants skips over a dense block of candidate variants because the number of haplotypes to test is too high
* allows the max-haplotypes parameter to be set on the command line
Cheers
Nick
=> Ability to increase the number of tested haplotypes on the command line

src/common/nanopolish_variant.cpp, src/nanopolish_haplotype.cpp
Hello,
I just updated the Debian package of nanopolish to 0.8.1 and these warnings scrolling along the screen somehow felt bad. Please apologize for not patching something more important. That said, we all anticipate positions of the size of a full genome which at least for the human exceeds the maximal position of a signed int, so this patch may eventually turn out to important after all :)
Please ping me if the Debian Linux distribution can do something else for you.
Kind regards,
Steffen
=> fprintf on size_t: %d -> %ul

src/common/logger.hpp
Fixing compilerer error about "'function' in namespace 'std' not naming a template type".
With Debian having transitioned to version 7 of the gcc/g++, this patch came rather natural ;) No idea about compatibility with gcc6.
=> logger.cpp - gcc 7 - <functional>

Makefile
support additional standard build flags
* apply the C preprocessor flags when building C code (not just C++ code)
* apply `LDFLAGS` when linking
Improve support for using externally installed libraries
* allow overriding the build settings without editing the Makefile
* allow use of an external htslib
=> Build flexibility

src/hmm/nanopolish_profile_hmm.cpp
It looks like Alphabet->get_name() was recently changed from a std::string to a char*, which was causing the following runtime error for me:
nanopolish: src/hmm/nanopolish_profile_hmm.cpp:40: float profile_hmm_score_set(const std::vector<HMMInputSequence>&, const HMMInputData&, uint32_t): Assertion `sequences[0].get_alphabet()->get_name() == "nucleotide"' failed.
Not sure if the cast is the desired solution.
=> Avoid comparison of char* and string literal

src/nanopolish_squiggle_read.cpp
Get a  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = '..', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0 as  fast5_close is missing.
Putting  fast5_close eradicated the issue, hopefully, I have put fast5_close in the correct place.
=> fix too many open files due to a missing file close

src/nanopolish_polya_estimator.cpp
Updated usage message for `polya` to indicate that we only support 1D direct RNA reads.
=> clarify usage message: only 1D direct RNA

src/alignment/nanopolish_eventalign.cpp, src/common/nanopolish_bam_processor.cpp, src/common/nanopolish_bam_processor.h, src/nanopolish_call_methylation.cpp
1. Changing the scheduling policy in the bam processor to dynamic
2. An option for increasing the batch size in nanopolish call-methylation (new option K)
3. Changing the default batch size in nanopolish call-methylation (K) to 512
With the previous scheduling policy (static scheduling) for 8 threads.
Percent of CPU this job got: 347%
Elapsed (wall clock) time (h:mm:ss or m:ss): 3:32.16
After changing the scheduling policy (dynamic scheduling now) for 8 threads.
Percent of CPU this job got: 657%
Elapsed (wall clock) time (h:mm:ss or m:ss): 2:08.48
After adding an option to increase the batch size. Now run with K=4096 batch size for 8 threads.
Percent of CPU this job got: 760%
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:55.87
How the performance varies with the number of threads is …
=> Performance improvements to nanopolish call-methylation

scripts/extract_reads_aligned_to_region.py, scripts/nanopolish_makerange.py, scripts/nanopolish_merge.py
Low level FASTA parser generator function``SimpleFastaParser`` was introduced in Biopython 1.61 back in February 2013, so the dependencies shouldn't matter.
This avoids the overhead of building ``SeqRecord`` objects etc, so is several times faster.
=> Use Biopython's string based FASTA parser

src/nanopolish_polya_estimator.cpp
* reorganized `nanopolish_polya_estimator.cpp` into discrete components: segmentation HMM class with inlined log-probability scoring; read-rate estimation; polya length estimation; and self-contained QC.
* use median of intra-read 5mer durations to estimate read rate rather than inferred by averaging across transcript samples.
=> Reorganized polya estimator with robust read rate estimates

src/alignment/nanopolish_eventalign.cpp, src/nanopolish_squiggle_read.cpp, src/nanopolish_squiggle_read.h
Add additional columns in the eventalign output file corresponding to events start and end indexes on the  raw signal. It works but can probably be optimized.
=> Add --signal-index option to event align

src/nanopolish_polya_estimator.cpp
A previous fix for the `--samples` flag broke the orientation assumption for the viterbi algorithm implementation in `SegmentationHMM` of the poly-A estimator. These commits fix the viterbi algorithm implementation.
=> SquiggleRead orientation fix

src/nanopolish_polya_estimator.cpp
The QC test that ensures soft-clipping is never more than 20% of the length of the total transcript length is a hold-over from an older version of the code that doesn't use the median event duration as a robust estimator of global read-rate for a given read. Removing it gives a ~50% improvement in yield (number of reads that have estimates) while keeping estimates almost the same. (For longer-length datasets, 80xA-100xA the estimates are ever so slightly better in distribution.)
=> Improve yield by deprecating pre-segmentation QC test

src/nanopolish_polya_estimator.cpp
* Moved the check for existence of events to the main estimator function `estimate_polya_for_single_read`;
* We now output a dummy row with a QC flag of `READ_FAILED_LOAD` if the fast5 path does not exist, or if there are no events in the squiggle read;
* shorten the read name in the `polya-durations` verbose output to the first six characters to save space
=> add guard to check squiggleread instances before segmentation

.travis.yml, Makefile
This fixes https://github.com/jts/nanopolish/issues/458 .
I needed to suppress verbose log, because maybe gcc-8 outputs more log than gcc-4.8. I faced Travis error because of exceeding of the limitation of the Travis log output length.
As a good result, after this pull-request, we can check entire Travis log from the Travis log page, without downloading the raw log file.
This is beneficial for development, isn't it?
=> Add the test case of latest version gcc 8 on Travis.

Makefile
I did refactoring for `Makefile`.
* Right now there is a mixture of "FOO = bar" (with space) and "FOO=bar" (without space).
I aligned with " = " (with space). 
Seeing ruby Makefile, it is aligned with the way.
https://github.com/ruby/ruby/blob/trunk/Makefile.in
* Add line break and escape "\" to shell code.
It looks easier to understand shell lines in `Makefile`.
* Add .PHONY target safely for non-file target.
=> Refactor Makefile.

.travis.yml, Makefile
In this pull-request, maybe we might need discussion.
The situation is when run "make clean", ".depend" task is run.
As we know, the task is always run.
I want to change this behavior.
Because when people want to remove files, the dependency installation starts. That's not intuitive.
I like to run the ".depend" when only "make nanopolish" is run.
And considering how to inject "depend" task, I think "make & make test" can be used instead of "make nanopolish & make test" after this pull-request.
How do you think?
=> Update not to run ".depend" task when running "make clean".

Makefile
This feature is to build with dependencies (`hdf5` and `eigen`)' version specified by environment variable. 
The benefits are
* We can upgrade the default version easily by changing 1 line in `Makefile`.
* Maybe we want to pin the dependency version when upgrading maintenance version, as we manage the version `v{major}.{minor}.{maintenance}`. In other words, we want to test the latest version of the dependency anytime. We might want to change the default dependency version in `Makefile` only when we upgrade major or minor version.
* Perhaps we want to test `nanopolish` with specific old version dependencies. In this mechanism, it is easier.
hdf5 latest version is 1.10.3.
https://portal.hdfgroup.org/display/support/Downloads
eigen latest version is 3.3.5.
http://bitbucket.org/eigen/eigen …
=> Update to build with specified version's dependencies.

docs/source/index.rst, docs/source/manual.rst
Fixed a flaw in the documentation that prevented the `polya` quickstart tutorial from appearing on the sidebar.
Added an additional entry to the manual.
=> add polya tutorial to index and add example usage

.travis.yml, Dockerfile-arm, Makefile
This PR is to add both `aarch64` (ARM 64-bit) and `armv7hl` (ARM 32-bit).
Right now working in progress. But I think it's worth to share in advance.
Here is the result.
https://travis-ci.org/junaruga/nanopolish/builds/444505171
There are some notes
* Using QEMU and Docker container technology to test ARM environment on Travis. [1][2]
* The running time of the added ARM test cases are longer.
In this issue, I would recommend to use conditional job [3] like this. This is only run for Travis cron mode or environment variable `CI_CRON` is set as `1` from Travis setting page.
```
+    - name: aarch64
+      sudo: required
+      env:
+        - ARCH=arm64
+      if: type = cron OR env(CI_CRON) = 1
```
* I am trying to skip to build hdfs5 from the source code. Instead of that use system-wide …
=> Add ARM case on Travis CI.

scripts/calculate_methylation_frequency.py
Changed the type of key used to a tuple.  The previous method would give errors if the chromosome name had a colon in it.
=> Changed keys to a tuple

DEVELOPERS.md
Added a new document titled `DEVELOPERS.md`, intended to be a collection of explanatory notes for developers (updating the bioconda release, contributing, pull requests, etc). Will grow to include further details as time goes on.
@jts , comments appreciated!
=> add document to explain development workflows

scripts/extract_reads_aligned_to_region.py
Commit ee6b01dfaa59a8db30c785b329bda93858d76f64 broke this script as it introduced new variable names but didn't change the old usages. This commit fixes the names.
=> Fix filehandle and name references

src/hmm/nanopolish_profile_hmm.cpp, src/nanopolish_call_variants.cpp, src/nanopolish_squiggle_read.cpp, src/nanopolish_squiggle_read.h
This is to avoid a name clash of the `PT_R7` and `PT_R9` enums with values defined by some architecture-specific header on PowerPC platforms.
Closes #883.
=> Rename PT_R[79] enums to PORETYPE_R[79]
