jts/nanopolish

- Dockerfile
- README.md
I had trouble getting nanopolish to compile (on mac OS) so I made a docker file to install requirements. 
If you're not familiar with docker usage is:
docker build . 
... Successfully built aa7f798df183 ...
docker run -it aa7f798df183 ./nanopolish
> Added dockerfile for easy requirements install

- src/alignment/nanopolish_eventalign.cpp
Loading a `fast5` file and the output of `eventalign` is not enough to figure out where the alignments are for the given read. The option fixes that problem.
> added option to print read names instead of indexes

- Makefile
- src/alignment/nanopolish_eventalign.h
- src/common/nanopolish_alphabet.cpp
- src/common/nanopolish_alphabet.h
- src/main/nanopolish.cpp
- src/nanopolish_call_variants.h
- src/nanopolish_consensus.h
- src/nanopolish_getmodel.h
- src/nanopolish_methyltest.cpp
- src/nanopolish_methyltrain.cpp
- src/nanopolish_methyltrain.h
- src/nanopolish_poremodel.cpp
- src/nanopolish_poremodel.h
- src/nanopolish_scorereads.cpp
- src/nanopolish_scorereads.h
- src/nanopolish_squiggle_read.h
Calculate per-event scoring of reads against a model, with infrastructure changes in methyltrain, alphabet, and poremodel to support.
> Scorereads

- src/common/logger.hpp
- src/common/logsumset.hpp
- src/nanopolish_methyltrain.cpp
- src/training_core.cpp
- src/training_core.hpp
First iteration, not tested yet. I'll come back to this.
> gaussian training in logspace

- src/common/logsum.cpp
- src/hmm/invgauss.hpp
- src/main/nanopolish.cpp
- src/nanopolish_methyltrain.cpp
- src/nanopolish_poremodel.cpp
- src/nanopolish_poremodel.h
- src/test/nanopolish_test.cpp
- src/training_core.cpp
- src/training_core.hpp
Currently, only one test for Gaussian training, which doesn't pass yet.
> test training

- src/alignment/nanopolish_alignment_db.cpp
- src/alignment/nanopolish_alignment_db.h
- src/alignment/nanopolish_eventalign.cpp
- src/common/nanopolish_variant.cpp
- src/hmm/nanopolish_hmm_input_sequence.h
- src/hmm/nanopolish_profile_hmm.cpp
- src/hmm/nanopolish_profile_hmm.h
- src/hmm/nanopolish_profile_hmm.inl
- src/nanopolish_call_variants.cpp
- src/nanopolish_poremodel.cpp
- src/nanopolish_squiggle_read.cpp
- src/nanopolish_squiggle_read.h
This will merge branch snp_calling_alternate_models as well as fixing #34 and adding support for SQK-MAP-006 latest 6mer models
> Bring master up to date with alternative models, fix some bugs

- src/common/alg.hpp
- src/common/fs_support.hpp
- src/main/nanopolish.cpp
- src/nanopolish_extract.cpp
- src/nanopolish_extract.h
- src/nanopolish_getmodel.cpp
- src/nanopolish_poremodel.cpp
- src/nanopolish_poremodel.h
- src/nanopolish_squiggle_read.cpp
- src/nanopolish_squiggle_read.h
- src/test/nanopolish_test.cpp
- nanopolish extract: extract fasta from preferred basecall read group
- group must have sequence as well as events
- extract includes basecall group in fasta read name
- squiggle read parses it and loads the appropriate structs
> nanopolish extract

- src/nanopolish_extract.cpp
> added option to extract fastq

- src/nanopolish_extract.cpp
print count of files processed and used
enable -v option
> tweak extract log messages

- src/nanopolish_extract.cpp
Updated read name computation to address changes in ONT software.
> fix extract read names

- src/nanopolish_extract.cpp
- src/nanopolish_extract.h
Implemented option to extract basecalls by basecaller name and version
> extract basecalls by basecaller name and version

- Makefile
Do not override users CFLAGS, CXXFLAGS, CC, CXX variables.
Ensure make stops upon an error in more places.
> More Makefile improvements

- src/nanopolish_polya_estimator.cpp
- src/nanopolish_squiggle_read.cpp
Use a hidden markov model to find polyadenylated regions within raw ONT direct RNA data.
> HMM-based Poly-A region estimator

- scripts/nanopolish_merge.py
Changing xrange -> range for python3 compatibility.
> range fix for python3

- docs/source/debug.rst
- docs/source/installation.rst
- docs/source/manual.rst
- docs/source/quickstart_consensus.rst
- docs/source/quickstart_eventalign.rst
A tutorial on how to help us debug nanopolish errors with `scripts/extract_reads_aligned_to_region.py`  for the readthedocs.
> Help us debug tutorial and the start of the eventalign tutorial

- src/nanopolish_polya_estimator.cpp
* emissions now come from trained probability distributions --- Gaussian, mixture of Gaussian, and Uniform;
* added two extra states (`CLIFF`, skippable `START`);
* removed `INCOMPETE` qc test (no longer necessary due to extra states);
* added `ADAPTER` qc test to check for large adapter regions (which indicates a mis-segmentation).
> Use trained emissions; add START/CLIFF states

- src/nanopolish_polya_estimator.cpp
* Add a TSV header to the output files
* Add a `--segmentation` flag to print segmentation of read instead of poly-A specific data
* Update usage message
* Fix `--window` flag
> output header and -s option

- src/nanopolish_call_variants.cpp
Option to make min-flanking-sequence configurable.
> make min-flanking-sequence configurable

- src/common/nanopolish_alphabet.h
- src/nanopolish_call_methylation.cpp
Hopefully these changes are less painful to look at! :)
> Methylation call changes v2

- scripts/calculate_methylation_frequency.py
This change is to match the changes to call-methylation.
> Changed header name in calculate_methylation_frequency.py.

- src/nanopolish_polya_estimator.cpp
* label HMM states via enum;
* rename `pos->position`, `transcr_start->transcript_start` in output header
> Descriptive HMM states via enum

- .travis.yml
Sorry, you have managed `.travis.yml` file with 4 spaces indent, right?
I wrongly updated with 2 spaces indent for previous pull-request.
This pull-request is to align with 4 spaces indent.
> Align with the indent 4 spaces in .travis.yml.

- src/nanopolish_raw_loader.cpp
Benchmark was done for call-methylation module using data at https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html
using the attached script.
The final answer with and without modifications are the same as verified using diff.
[script.sh.txt](https://github.com/jts/nanopolish/files/2478574/script.sh.txt)
> One dimensional array for faster multithreaded performance of call-methylation

- docs/source/quickstart_polya.rst
Added a quickstart tutorial for polyadenylation-calling to the documentation.
> add a quickstart tutorial for the polya subprogram

- src/nanopolish_polya_estimator.cpp
Update the Segmentation HMM class to generate correct segmentations on SQK-RNA-002 reads.
* Initial state probabilities are now 100% on `START` state;
* `START` state emission distribution is now a mixture of a Uniform and a Gaussian.
* Remove the post-segmentation QC check that ensures a `LEADER` segment must be > 200 samples.
> update segmentation HMM model to handle SQK-RNA-002 kit

- src/nanopolish_polya_estimator.cpp
Merge fix to polya model so that SQK-RNA-002 is supported.
> Sqk rna 002 modelfix

- scripts/calculate_methylation_frequency.py
this commit removes two unnecessary imports from `scripts/calculate_methylation_frequency.py`
> removing unnecessary imports

- Makefile
* Fix include path for system installed eigen library]
* Allow users to supply htslib include path from commandline
> Fixes for compiling with system libraries

- README.md
I noticed that the methylation paper URL was incorrect and not working. I've updated it to the current one.
> Updated methylation paper URL

- .github/workflows/nanopolish.yaml
Added a basic GitHub actions YAML file to eventually replace Travis-CI
> Add GitHub actions

- .github/workflows/nanopolish.yaml
Added the `workflow_dispatch` action to allow manual execution of action to build and test.
> added workflow_dispatch to manually run action
